### PR TITLE
fix size_t on windows

### PR DESCRIPTION
**Pull request by blaenk**
[On windows](https://github.com/rust-lang/rust/blob/master/src/liblibc/lib.rs#L1609), `c_ulong` is [set to `u32`](https://github.com/rust-lang/rust/blob/master/src/liblibc/lib.rs#L1745). This fixes `size_t` to actually be equal to `size_t`, which is more appropriate.

This allows this to build on Windows, awesome!

### CODE REVIEW

**Comment by blaenk** [comment]
Would appreciate a crate version bump when you get a chance.

**Comment by winding-lines** [comment]
Done :)

On Wed, Jul 8, 2015 at 12:57 PM, Jorge Israel Peña <notifications@github.com

**Comment by winding-lines** [comment]
@blaenk I am trying to integrate with appveyor for automated windows builds.
https://ci.appveyor.com/project/winding-lines/sass-sys/build/1.0.4/job/q6gq1ie9r8sy8vmv

The build.rs file needs to change, do you have a working one you could share? I do not have access to a windows machine.

**Comment by blaenk** [comment]
Awesome! Appveyor would be great to ensure we stay windows compatible.

It worked for me on my windows computer. I'm pretty sure the reason it failed is because it couldn't find the `make` command to run it, that or gcc or any of the others. I'm pretty sure it's `make` though. I installed [mingw-w64](http://mingw-w64.org/doku.php). The weird thing is though that it includes make as `mingw32-make`, so I had to create a copy of it named `make`, instead of modifying the build.rs script to use `mingw32-make` on windows. Not sure what the best option is here.

> What's the difference between make and mingw32-make?
> 
> The "native" (i.e.: MSVCRT dependent) port of make is lacking in some functionality and has modified functionality due to the lack of POSIX on Win32. There also exists a version of make in the MSYS distribution that is dependent on the MSYS runtime. This port operates more as make was intended to operate and gives less headaches during execution. Based on this, the MinGW developers/maintainers/packagers decided it would be best to rename the native version so that both the "native" version and the MSYS version could be present at the same time without file name collision.

[source](http://www.mingw.org/wiki/FAQ)

So in summary It think you'd have to add a way to download and use mingw-w64, probably have to add it to the PATH but not sure. I'm not sure how that would be done in appveyor, maybe I can find a package that does this so we can copy it.

Then the build.rs script will have to be changed so that on windows it uses `mingw32-make` instead of `make`. Maybe something like:

``` rust
#[cfg(windows)]
fn command_name() -> &'static str { "mingw32-make" }

#[cfg(not(windows))]
fn command_name() -> &'static str { "make" }
```

Then call `command()` to create the `Command` instance. I asked on the mingw-w64 channel and they said that it's safe to assume mingw32-make on windows, and it's better if we provide some sort of override, probably a MAKE env var.

Here's another option, which runs `make` and if it fails because it couldn't find the `make` command then it attempts to run the `mingw32-make` command.

``` rust
use std::process::{Command, ExitStatus};
use std::io;

fn make_it() -> io::Result<ExitStatus> {
    match Command::new("make").status() {
        ok @ Ok(_) => ok,
        Err(e) => match e.kind() {
            io::ErrorKind::NotFound => Command::new("mingw32-make").status(),
            _ => return Err(e),
        }
    }
}
```

Not sure which approach is better. The first one is certainly simpler.

So to recap, things that the appveyor setup needs to do:

1. install mingw-w64
2. add it to PATH probably, though maybe just referring to mingw32-make by absolute path works too
3. run mingw32-make on windows, make on everything else. perhaps provide some override, but not a high priority at the moment

**Comment by blaenk** [comment]
Awesome! I just noticed that libsass actually has the relevant things in its appveyor file!

[Check it out](https://github.com/sass/libsass/blob/master/appveyor.yml)!

**Comment by blaenk** [comment]
In particular the install section which downloads and adds mingw-w64 to the path.

**Pull request merged**
